PlaceOrderController.php - before executing the vat check, the vat is validated for length
plentymarkets/plugin-io pull request #1059
Opened 2021-12-30 18:16 UTC by cjohannsen

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/plentyshop

2022-01-27 09:48 UTC, ggottwald approved these changes

2022-01-27 09:51 UTC, ggottwald requested changes, later dismissed
.

2022-01-27 09:54 UTC, ggottwald approved these changes, later dismissed
test approve

2022-01-27 09:56 UTC, ggottwald approved these changes, later dismissed
test approve

2022-02-10 08:00 UTC, stentrop approved these changes

2022-02-10 08:41 UTC, merged