FIX property selection names
plentymarkets/plugin-io pull request #1070
Opened 2022-01-27 14:10 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/plentyshop
@estafilarakis

2022-01-27 15:06 UTC, estafilarakis requested changes

2022-01-27 15:06 UTC, estafilarakis commented on src/Extensions/Filters/PropertyNameFilter.php
> +            $property['value'] = array_slice($propertyValueDecoded, 0, 1)[0];
Würde hier nicht `array_shift` ausreichen? Dürfte zumindest schneller sein, als erst einen Array-Ausschnitt zu erstellen, um die erste Position zu ziehen.
```suggestion
            $property['value'] = array_shift($propertyValueDecoded);
```

2022-01-28 08:54 UTC, estafilarakis submitted a review, later dismissed

2022-01-28 13:52 UTC, stentrop commented on src/Extensions/Filters/PropertyNameFilter.php
> +        if(is_array($propertyValueDecoded) && count($propertyValueDecoded)) {
```suggestion
        if (is_array($propertyValueDecoded) && count($propertyValueDecoded)) {
```

2022-01-28 14:00 UTC, stentrop submitted a review, later dismissed

2022-01-28 14:01 UTC, stentrop approved these changes

2022-01-31 08:50 UTC, merged