copy of #1182, make sure that new function uses its own variable
plentymarkets/plugin-io pull request #1186
Opened 2023-10-23 12:37 UTC by felixgehrmann

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Changes to routes were replicated in webshop package
- [ ] Plugin can be built

@plentymarkets/plentyshop

Supersedes #1182

2023-10-25 20:11 UTC, stentrop requested changes, later dismissed

2023-10-25 20:11 UTC, stentrop commented on src/Extensions/Constants/ShopUrls.php
> +                return $trackingURLs;
Return type is string here, is this compatible ?

2023-10-26 07:30 UTC, stentrop commented on src/Extensions/Constants/ShopUrls.php
> +                return $trackingURLs;
its not see: https://github.com/plentymarkets/plugin-ceres/pull/3444

2024-02-27 07:43 UTC, Dominik2809 requested changes

2024-02-27 07:43 UTC, Dominik2809 commented on src/Extensions/Constants/ShopUrls.php
> +     * @return string[]
array

2024-03-01 08:20 UTC, Dominik2809 approved these changes

2024-03-05 08:55 UTC, merged