FIX remove basket items that have no name in the current language
plentymarkets/plugin-io pull request #163
Opened 2018-03-07 09:14 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested

@plentymarkets/ceres-io

2018-03-07 13:19 UTC, felixdausch approved these changes

2018-03-07 13:23 UTC, felixdausch requested changes

2018-03-07 13:23 UTC, felixdausch commented on src/Services/BasketService.php
> +                /** @var TemplateConfigService $templateConfigService */
Willst du an dieser Stelle nicht lieber einen Fehlercode oder Translation-Key ausgeben und die Übersetzung in Ceres vornehmen? So schaffen wir eine weitere Anforderung an Template-Plugins, die mit IO kompatibel sein wollen.

2018-03-16 12:13 UTC, felixdausch submitted a review, later dismissed

2018-09-12 05:13 UTC, dbohla commented
@Dominik2809 Was ist mit diesem PR, noch benötigt?

2018-10-19 13:46 UTC, closed without merging