Fix/gender for contact
plentymarkets/plugin-io pull request #185
Opened 2018-04-09 07:07 UTC by mdierkes

- changes gender for contact by updating first billingaddress

Ceres: https://github.com/plentymarkets/plugin-ceres/pull/394

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2018-04-09 08:33 UTC, Dominik2809 submitted a review, later dismissed

2018-04-09 11:16 UTC, Dominik2809 submitted a review, later dismissed

2018-04-11 06:33 UTC, cjohannsen commented on src/Services/CustomerService.php
> +                    $contactData['options'] =
@Dominik2809 is there a better way to set option types?

2018-04-12 15:31 UTC, Dominik2809 requested changes
- check at update and delete
- unnecessary else in AddressValidator

2018-04-13 07:53 UTC, Dominik2809 approved these changes

2018-04-13 11:08 UTC, merged