fix vat rates and basket reset logic
plentymarkets/plugin-io pull request #214
Opened 2018-05-24 17:59 UTC by stentrop

### All changes meet the following requirements
- [x] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2018-06-01 10:55 UTC, felixdausch requested changes

2018-06-01 10:55 UTC, felixdausch commented on src/Services/OrderTotalsService.php
> +        if(strlen($couponType) > 0)
Ist diese Abfrage nötig, wenn du direkt danach auf `$couponType == OrderItemType::GIFT_CARD` oder `$couponType == OrderItemType::PROMOTIONAL_COUPON` prüfst?

2018-06-01 13:49 UTC, stentrop commented on src/Services/OrderTotalsService.php
> +        if(strlen($couponType) > 0)
das stimmt wohl

2018-06-04 11:03 UTC, felixdausch submitted a review, later dismissed

2018-06-05 11:07 UTC, Dominik2809 requested changes
coupon isset

2018-06-05 11:15 UTC, Dominik2809 submitted a review, later dismissed

2018-06-05 11:17 UTC, Dominik2809 approved these changes

2018-06-05 11:18 UTC, merged