Feature/search manufacturer by
plentymarkets/plugin-io pull request #331
Opened 2018-11-22 14:02 UTC by maxiroellplenty

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io 

## Added: 
* Manufacturer Service & Search Preset

2019-01-14 09:07 UTC, Dominik2809 requested changes

2019-01-14 09:07 UTC, Dominik2809 commented on src/Services/ItemSearch/Factories/VariationSearchFactory.php
> +     * Filter variations by multiple availability ids.
wrong comment

2019-01-14 09:07 UTC, Dominik2809 commented on src/Services/ItemListService.php
> +    public function getItemList( $type, $id = null, $sorting = null, $maxItems = 0)
add space again

2019-01-16 12:05 UTC, felixdausch requested changes

2019-01-16 12:05 UTC, felixdausch commented on src/Extensions/TwigServiceContainer.php
> +    public function getItemManufacturerService()
die Zugriffsmethoden in dieser Klasse werden ohne den `Service`-Suffix angeben. Sprich `getItemManufacturer`. Diese Klasse dient lediglich dazu, die Services aus Twig heraus anzusprechen. Dies passiert über die globale Variable `services`. Daher wäre der Suffix an dieser Stelle doppelt.

2019-01-16 12:05 UTC, felixdausch commented on src/Services/ItemManufacturerService.php
> +class ItemManufacturerService
Wird die Klasse überhaupt verwendet? Andernfalls bitte wieder entfernen.

2019-01-21 09:28 UTC, maxiroellplenty commented
restart tests

2019-01-24 17:07 UTC, felixdausch commented on src/Services/ItemManufacturerService.php
> +class ItemManufacturerService
Reminder

2019-01-28 10:13 UTC, maxiroellplenty commented on src/Services/ItemManufacturerService.php
> +class ItemManufacturerService
@felixdausch done, wurde tatsächlich nicht verwendet.

2019-01-30 13:44 UTC, Dominik2809 approved these changes

2019-01-30 13:52 UTC, felixdausch approved these changes

2019-01-30 16:00 UTC, merged