Feature/show category after login
plentymarkets/plugin-io pull request #396
Opened 2019-02-27 12:48 UTC by stentrop

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-02-27 20:04 UTC, felixdausch requested changes

2019-02-27 20:04 UTC, felixdausch commented on src/Services/CategoryService.php
> +        $customerLoggedIn = false;
wir diese Variable überhaupt verwendet? Später wird `$loggedIn` initialisiert und geprüft.

2019-02-28 07:25 UTC, stentrop commented on src/Services/CategoryService.php
> +        $customerLoggedIn = false;
Hab sie wieder entfernt war nur ein Rest von einem Test.

2019-02-28 07:26 UTC, felixdausch approved these changes

2019-03-22 07:13 UTC, merged