Extend contact email optional with cc and bcc emails and the subject with the orderid
plentymarkets/plugin-io pull request #427
Opened 2019-03-21 17:18 UTC by Lauflust

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io 

Requires Ceres update
Ceres PR: https://github.com/plentymarkets/plugin-ceres/pull/1002

2019-04-24 15:01 UTC, felixdausch requested changes

2019-04-24 15:01 UTC, felixdausch commented on src/Services/ContactMailService.php
> +            $contactData['subject'] = $contactData['subject'] . " [OrderId: " . $contactData['orderId'] . "]";
@Lauflust 
An dieser Stelle wäre es sinnvoller, auf die Mehrsprachigkeit zurückzugreifen:

```
use Plenty\Plugin\Translation\Translator;
...
$translator = pluginApp(Translator::class);
$contactData['subject'] = $translator->trans(
  'Ceres::Template.contactMailSubject', 
  [
    'subject' => $contactData['subject'],
    'orderId' => $contactData['orderId']
  ]
);
```

Auf diese Weise kann jeder Anwender die Formatierung für den Betreff selbst vornehmen.

2019-04-27 20:12 UTC, Lauflust commented on src/Services/ContactMailService.php
> +            $contactData['subject'] = $contactData['subject'] . " [OrderId: " . $contactData['orderId'] . "]";
Guter Einwand! Ich werde diese Änderung übernehmen.

Dann muss aber im Handbuch erklärt werden, dass die Übersetzung "_contactMailSubject_" nur verwendet wird, wenn die Einstellung "_extend_orderid_to_mail_subject_" aktiviert ist. _(Und wie es mit den Platzhaltern funktioniert)_

2019-05-02 08:03 UTC, felixdausch commented on src/Services/ContactMailService.php
> +            $contactData['subject'] = $contactData['subject'] . " [OrderId: " . $contactData['orderId'] . "]";
Hallo @Lauflust,

ein weiterer Vorteil der Mehrsprachigkeit ist, dass die Einstellung `extend_orderid_to_mail_subject` dadurch überflüssig wird. Der Standardwert der Übersetzung wäre nur die Variable `subject`, sodass der aktuelle Zustand wieder hergestellt wäre. Der Anwender kann dann optional diesen Text ändern.

2019-05-02 09:36 UTC, Lauflust commented on src/Services/ContactMailService.php
> +            $contactData['subject'] = $contactData['subject'] . " [OrderId: " . $contactData['orderId'] . "]";
Hi @felixdausch ,
ich hab ganz übersehen, dass du `extend_orderid_to_mail_subject` raus genommen hast..
Klar, das würde Sinn machen!

2019-05-02 09:54 UTC, felixdausch approved these changes

2019-05-02 10:52 UTC, merged