fix lang in confirmation link
plentymarkets/plugin-io pull request #433
Opened 2019-03-27 16:13 UTC by stentrop

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-03-28 15:23 UTC, felixdausch requested changes

2019-03-28 15:23 UTC, felixdausch commented on src/Controllers/ItemSearchController.php
> +        AuthGuard::redirect($url, ['query' => $query]);
Bitte `ShopURLs::$search` verwenden. Dort sollte die Sprache bereits enthalten sein

2019-03-28 15:49 UTC, maxiroellplenty submitted a review, later dismissed

2019-04-24 13:33 UTC, felixdausch approved these changes

2019-04-24 13:59 UTC, merged