Fix/post office profile change reset address
plentymarkets/plugin-io pull request #434
Opened 2019-03-27 16:46 UTC by cjohannsen

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-03-28 09:09 UTC, Dominik2809 submitted a review, later dismissed

2019-04-05 07:54 UTC, felixdausch requested changes

2019-04-05 07:54 UTC, felixdausch commented on src/Extensions/Basket/IOFrontendShippingProfileChanged.php
> +        $selectedDeliveryAddress = $customerService->getAddress($deliveryAddressId, 2);
Bitte `IO\Builder\Order\AddressType` verwenden

2019-04-05 07:54 UTC, felixdausch commented on src/Extensions/Basket/IOFrontendShippingProfileChanged.php
> +            if (!$isPostOfficeAndParcelBoxActive && ($isAddressPostOffice || $isAddressParcelBox))
Diese Abfrage ist überflüssig. Es wird lediglich geprüft, ob eine der unteren Bedingungen zutrifft. Du kannst also auch einfach direkt den inneren Teil prüfen.

2019-04-05 07:54 UTC, felixdausch commented on src/Extensions/Basket/IOFrontendUpdateDeliveryAddress.php
> +        {
Abfrage überflüssig (s.o.)

2019-04-05 08:43 UTC, cjohannsen commented on src/Extensions/Basket/IOFrontendShippingProfileChanged.php
> +        $selectedDeliveryAddress = $customerService->getAddress($deliveryAddressId, 2);
done

2019-04-05 08:43 UTC, cjohannsen commented on src/Extensions/Basket/IOFrontendShippingProfileChanged.php
> +            if (!$isPostOfficeAndParcelBoxActive && ($isAddressPostOffice || $isAddressParcelBox))
done

2019-04-05 08:43 UTC, cjohannsen commented on src/Extensions/Basket/IOFrontendUpdateDeliveryAddress.php
> +        {
done

2019-04-05 08:51 UTC, felixdausch approved these changes

2019-04-05 09:17 UTC, merged