ADD routing for static pages
plentymarkets/plugin-io pull request #575
Opened 2019-09-01 15:06 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-09-02 09:34 UTC, felixdausch requested changes

2019-09-02 09:34 UTC, felixdausch commented on resources/lang/en/Config.properties
> +routingEnabledRoutesPossibleValuePageNotFound="Page not found"
```suggestion
routingEnabledRoutesPossibleValuePageNotFound= Page not found
```

2019-09-03 07:19 UTC, stentrop approved these changes

2019-09-03 07:27 UTC, felixdausch approved these changes

2019-09-03 07:59 UTC, merged