Feature/sb static pages/newsletter unsubscribe routing
plentymarkets/plugin-io pull request #587
Opened 2019-09-13 13:44 UTC by felixgehrmann

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-09-13 14:13 UTC, stentrop approved these changes

2019-09-13 16:33 UTC, felixgehrmann commented on src/Middlewares/Middleware.php
> +use Plenty\Modules\RestDocumentation\Export\Models\Auth;
```suggestion

```

2019-09-16 14:38 UTC, felixdausch requested changes

2019-09-16 14:38 UTC, felixdausch commented on src/Providers/IORouteServiceProvider.php
> +                return pluginApp(CategoryController::class)->redirectToCategory($shopUrls->newsletterOptOut, '/newsletter/unsubscribe');
Bitte nicht mehr direkt auf das Ergebnis von `pluginApp()` zugreifen. Das kann zu Fehlern beim Plugin-Build führen:
```
/** @var CategoryController $categoryController **/
$categoryController = pluginApp(CategoryController::class);
return $categoryController->redirectToCategory();
```

2019-09-16 16:43 UTC, felixgehrmann commented on src/Providers/IORouteServiceProvider.php
> +                return pluginApp(CategoryController::class)->redirectToCategory($shopUrls->newsletterOptOut, '/newsletter/unsubscribe');
done

2019-09-17 07:19 UTC, felixdausch requested changes

2019-09-17 07:19 UTC, felixdausch commented on src/Providers/IORouteServiceProvider.php
> +use Plenty\Plugin\Routing\Route;
Wird die Klasse `Route` noch verwendet?

2019-09-17 07:36 UTC, felixgehrmann commented on src/Providers/IORouteServiceProvider.php
> +use Plenty\Plugin\Routing\Route;
Tatsächlich nicht. Durchs auto-folding meiner IDE geht mir das immer durch die Lappen. 
Done.

2019-09-17 09:52 UTC, felixdausch approved these changes

2019-09-17 11:52 UTC, merged