VariationList - add variation property group mutator
plentymarkets/plugin-io pull request #589
Opened 2019-09-13 16:35 UTC by cjohannsen

This change is required for 

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-09-17 11:02 UTC, felixdausch requested changes
Warum erstellst du eine neue Route anstatt bei `GET /rest/io/itemWishList` direkt die Liste an Artikeln zurückzugeben?

2019-09-17 12:24 UTC, cjohannsen commented
> Warum erstellst du eine neue Route anstatt bei `GET /rest/io/itemWishList` direkt die Liste an Artikeln zurückzugeben?

Die alte Route (welche nur die IDs zurück liefert) wird weiterhin von der TopBar verwendet um die Zahl hinter dem Herzchen zu rendern. Hast du eine gute Idee wie man das in eine Route packen kann?

2019-09-17 13:29 UTC, felixdausch requested changes

2019-09-17 13:29 UTC, felixdausch commented on src/Controllers/ItemWishListController.php
>              false
Wir können jetzt sogar die WishList-Seite cachen lassen!

2019-09-17 13:34 UTC, felixdausch commented
> Die alte Route (welche nur die IDs zurück liefert) wird weiterhin von der TopBar verwendet um die Zahl hinter dem Herzchen zu rendern. Hast du eine gute Idee wie man das in eine Route packen kann?

1. Entweder wir hängen den count mit an den Basket. Der wird bereits initial per rest geladen. Wir würden so sogar einen ganzen Rest-Call sparen.
2. Wir laden auch in der TopBar alle Artikel der Wunschliste. Im Normalfall (und aus sicht von Suchmaschinen) ist die Wunschliste sowieso leer, sodass es keinen Unterschied bei der Performance macht.
3. Du hängst einen GET-Paramter an die URL an (`?compact=1`), um nur die IDs zu laden.

Ich persönlich fände Option 1 am besten.

2019-09-17 15:03 UTC, cjohannsen commented
> > Die alte Route (welche nur die IDs zurück liefert) wird weiterhin von der TopBar verwendet um die Zahl hinter dem Herzchen zu rendern. Hast du eine gute Idee wie man das in eine Route packen kann?
> 
> 1. Entweder wir hängen den count mit an den Basket. Der wird bereits initial per rest geladen. Wir würden so sogar einen ganzen Rest-Call sparen.
> 2. Wir laden auch in der TopBar alle Artikel der Wunschliste. Im Normalfall (und aus sicht von Suchmaschinen) ist die Wunschliste sowieso leer, sodass es keinen Unterschied bei der Performance macht.
> 3. Du hängst einen GET-Paramter an die URL an (`?compact=1`), um nur die IDs zu laden.
> 
> Ich persönlich fände Option 1 am besten.

👍 
Ich habe die Option 1 umgesetzt.

2019-09-17 15:17 UTC, felixdausch approved these changes

2019-09-18 09:07 UTC, felixdausch requested changes

2019-09-18 09:07 UTC, felixdausch commented on src/Api/Resources/ItemWishListResource.php
> +        $items = $itemListService->getItemList(ItemListService::TYPE_WISH_LIST, null, null, null, null);
```suggestion
        $items = $itemListService->getItemList(ItemListService::TYPE_WISH_LIST);
```

Die Parameter `$id`, `$sorting`, `$maxItems` und `$crossSellingRelation` haben alle einen default-wert und müssen daher nicht explizit mit `null` angegeben werden.

2019-09-18 09:40 UTC, cjohannsen commented
Restart test.

2019-09-18 15:07 UTC, felixdausch approved these changes

2019-09-18 15:13 UTC, merged