Feature/sb static pages/changemail routing
plentymarkets/plugin-io pull request #592
Opened 2019-09-16 08:50 UTC by felixgehrmann

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-09-16 13:28 UTC, felixdausch requested changes

2019-09-16 13:28 UTC, felixdausch commented on src/Api/Resources/CustomerMailResource.php
> +            $newEmailLink = $domain . ($lang != $defaultLang ? '/' . $lang : ''). '/change-mail/'. $userDataHash->contactId . '/' . $userDataHash->hash;
Bleibt es für die alten URLs bei der Struktur `/change-mail/{contactId}/{hash}` oder wird die sich auch auf die Verwendung von QueryParams ändern?

2019-09-16 14:58 UTC, felixgehrmann commented on src/Api/Resources/CustomerMailResource.php
> +            $newEmailLink = $domain . ($lang != $defaultLang ? '/' . $lang : ''). '/change-mail/'. $userDataHash->contactId . '/' . $userDataHash->hash;
Wenn ich das richtig verstanden habe, dann ist, wenn die CategoryId <= 0 ist, die alte Struktur verwendet. Der Link ist damit der alte.

2019-09-16 16:08 UTC, Dominik2809 commented on src/Api/Resources/CustomerMailResource.php
> +            $newEmailLink = $domain . ($lang != $defaultLang ? '/' . $lang : ''). '/change-mail/'. $userDataHash->contactId . '/' . $userDataHash->hash;
Bei den alten URLs bleibt es so, also keine query params.

2019-09-16 16:30 UTC, felixgehrmann commented on src/Api/Resources/CustomerMailResource.php
> +            $newEmailLink = $domain . ($lang != $defaultLang ? '/' . $lang : ''). '/change-mail/'. $userDataHash->contactId . '/' . $userDataHash->hash;
Dann geh ich davon aus, dass der Code so korrekt ist.

2019-09-17 10:56 UTC, felixdausch requested changes

2019-09-17 10:56 UTC, felixdausch commented on resources/lang/de/Config.properties
> +routingCategoryChangeMail = Kategorie für Ändern der E-Mail-Adresse
@fmutschler Noch ein Anwendungsfall zu diesem Thema https://github.com/plentymarkets/plugin-ceres/pull/1470#discussion_r324717690

2019-09-18 09:18 UTC, felixdausch approved these changes

2019-09-18 09:19 UTC, merged