FIX Items with coupon restriction
plentymarkets/plugin-io pull request #650
Opened 2019-10-29 15:44 UTC by cjohannsen

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-10-30 14:04 UTC, felixdausch reviewed
Gibt es einen bestimmten Grund, warum du diese Prüfung in IO und nicht in den Kern eingebaut hast?

2019-10-31 14:16 UTC, cjohannsen commented
> Gibt es einen bestimmten Grund, warum du diese Prüfung in IO und nicht in den Kern eingebaut hast?

Ich habe mich mit @Dominik2809 zusammen gesetzt und er hat mir diese Stelle empfohlen. Wenn du darin einen Nachteil siehst, können wir gerne noch mal zusammen eine geeignetere Stelle finden.

2019-10-31 14:37 UTC, stentrop commented
Ich hätte vorgeschlagen ein Hook im Kern zu verwenden, der könnte z.B auf BeforeBasketItemAdd hören. Das wäre ähnlich zu CheckItemStock.

2019-11-04 12:52 UTC, stentrop requested changes

2019-11-04 12:52 UTC, stentrop commented on src/Builder/Order/OrderItemBuilder.php
> +                if ($exception->getCode() === 4)
```suggestion
                if ($exception->getCode() === BasketItemCheckException::COUPON_REQUIRED)
```

2019-11-04 12:56 UTC, stentrop approved these changes

2019-11-06 14:15 UTC, merged

2020-05-13 15:40 UTC, maxhelligeplenty commented
Hallo  ,
stentrop requested changes on this pull request.



> @@ -139,26 +142,33 @@ public function fromBasket(Basket $basket, array $items):array
             }
 			catch(BasketItemCheckException $exception)
             {
-                $itemsWithoutStock[] = [
-                    'item' => $item,
-                    'stockNet' => $exception->getStockNet()
-                ];
+                if ($exception->getCode() === 4)

```suggestion
                if ($exception->getCode() === BasketItemCheckException::COUPON_REQUIRED)
```

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/650#pullrequestreview-311047175

Test.test.test

2020-05-13 15:40 UTC, maxhelligeplenty commented
Hallo  ,
stentrop approved this pull request.





-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/650#pullrequestreview-311049518

Test.test.test