Check for contentLinkId and redirect to login, if not already logged in
plentymarkets/plugin-io pull request #653
Opened 2019-10-30 17:20 UTC by felixgehrmann

### All changes meet the following requirements
- [ ] Changelog entry was added
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io

2019-10-31 15:02 UTC, felixdausch requested changes

2019-10-31 15:02 UTC, felixdausch commented on src/Controllers/CategoryController.php
> +                $guard->assertOrRedirect( true, $shopUrls->login );
Hier solltest du einen Backlink mit angeben, damit man nach erfolgreichem Login wieder auf die Confirmation geleitet wird, so wie hier:
https://github.com/plentymarkets/plugin-io/blob/stable/src/Services/OrderService.php#L331

2019-10-31 15:02 UTC, felixdausch commented on src/Controllers/CategoryController.php
> +            if ($request->get('contentLinkId', false))
Du solltest zusätzlich noch prüfen, ob den User noch nicht eingeloggt ist. Am besten über `CustomerService::getContactId() <= 0`

2019-11-04 10:01 UTC, felixgehrmann commented on src/Controllers/CategoryController.php
> +                $guard->assertOrRedirect( true, $shopUrls->login );
@felixdausch Auf normalen Content und auf Login-Widget basierten Content funktioniert di Weiterleitung über Backlink automatisch?
Übersehe ich bei meiner Änderung einen speziellen Fall?

2019-11-04 10:46 UTC, felixgehrmann commented on src/Controllers/CategoryController.php
> +                $guard->assertOrRedirect( true, $shopUrls->login );
Bzw. der AuthGuard setzt automatisch Backlinks

2019-11-04 11:20 UTC, felixdausch approved these changes

2019-11-04 11:53 UTC, merged

2020-05-13 15:16 UTC, maxhelligeplenty commented
Hallo  ,
felixgehrmann commented on this pull request.



> @@ -194,6 +194,15 @@ private function renderCategory($category, $params = [])
             );
             RouteConfig::overrideCategoryId(RouteConfig::CONFIRMATION, $category->id);
 
+            if ($request->get('contentLinkId', false))
+            {
+                /** @var ShopUrls $shopUrls */
+                $shopUrls = pluginApp(ShopUrls::class);
+                /** @var AuthGuard $guard */
+                $guard = pluginApp(AuthGuard::class);
+                $guard->assertOrRedirect( true, $shopUrls->login );

@felixdausch Auf normalen Content und auf Login-Widget basierten Content funktioniert di Weiterleitung über Backlink automatisch?
Übersehe ich bei meiner Änderung einen speziellen Fall?

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/653#discussion_r341970571

Test.test.test

2020-05-13 15:17 UTC, maxhelligeplenty commented
Hallo  ,
felixgehrmann commented on this pull request.



> @@ -194,6 +194,15 @@ private function renderCategory($category, $params = [])
             );
             RouteConfig::overrideCategoryId(RouteConfig::CONFIRMATION, $category->id);
 
+            if ($request->get('contentLinkId', false))
+            {
+                /** @var ShopUrls $shopUrls */
+                $shopUrls = pluginApp(ShopUrls::class);
+                /** @var AuthGuard $guard */
+                $guard = pluginApp(AuthGuard::class);
+                $guard->assertOrRedirect( true, $shopUrls->login );

Bzw. der AuthGuard setzt automatisch Backlinks

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/653#discussion_r341989260

Test.test.test

2020-05-13 15:37 UTC, maxhelligeplenty commented
Hallo  ,
felixdausch approved this pull request.





-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/653#pullrequestreview-311006342

Test.test.test

2020-05-13 15:39 UTC, maxhelligeplenty commented
Hallo  ,
Merged #653 into beta.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/653#event-2767404791

Test.test.test