FIX do not append trailing slash if query params are present in the url
plentymarkets/plugin-io pull request #657
Opened 2019-11-04 13:10 UTC by Dominik2809

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2019-11-04 14:19 UTC, felixdausch requested changes

2019-11-04 14:19 UTC, felixdausch commented on src/Services/UrlBuilder/UrlQuery.php
> +        if($this->hasQueryParams($this->path))
Ist hier die Prüfung wirklich notwendig? Kannst du nicht pauschal am `?` trennen. Ggf. ist $queryParams dann nicht gefüllt.

2019-11-04 14:19 UTC, felixdausch commented on src/Services/UrlBuilder/UrlQuery.php
> +        $trailingSlash = self::shouldAppendTrailingSlash() && !$this->hasTralingSlash($this->path) ? "/" : "";
Du solltest nach dem Splitten an `?` den Trailing Slash pauschal entfernen, falls vorhanden und ihn dann ggf. wieder hinzufügen. So fängst du auch den Fall, dass ein Slash da ist aber nicht da sein soll ab.

2019-11-04 15:10 UTC, felixdausch requested changes

2019-11-04 15:10 UTC, felixdausch commented on src/Services/UrlBuilder/UrlQuery.php
> +        return $this->path . $trailingSlash . $queryParams;
```
list($path, $queryParams) = explode('?', $this->path);
if($path[strlen($path)-1] == '/')
{
    $path = substr($path, 0, -1);
}
$queryParams = strlen($queryParams) ? "?" . $queryParams : "";

$trailingSlash = self::shouldAppendTrailingSlash() ? "/" : "";

if ( $includeLanguage && strpos($path, '/'.$this->lang) !== 0)
{
    return '/' . $this->lang . $path . $trailingSlash . $queryParams;
}
elseif(strlen($path) == 0)
{
    return  "/";
}

return $path . $trailingSlash . $queryParams
```

2019-11-04 15:21 UTC, felixdausch submitted a review, later dismissed

2019-11-06 10:50 UTC, felixdausch approved these changes

2019-11-07 16:27 UTC, merged

2020-05-13 15:40 UTC, maxhelligeplenty commented
Hallo  ,
### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io 
You can view, comment on, or merge this pull request online at:

  https://github.com/plentymarkets/plugin-io/pull/657

-- Commit Summary --

  * FIX do not append trailing slash if query params are present in the url

-- File Changes --

    M src/Services/UrlBuilder/UrlQuery.php (14)

-- Patch Links --

https://github.com/plentymarkets/plugin-io/pull/657.patch
https://github.com/plentymarkets/plugin-io/pull/657.diff

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/657


Test.test.test

2020-05-13 16:04 UTC, maxhelligeplenty commented
Hallo  ,
felixdausch requested changes on this pull request.



> @@ -86,19 +86,28 @@ public function toRelativeUrl( bool $includeLanguage = false )
         {
             return null;
         }
+    
+        $queryParams = '';
+        if($this->hasQueryParams($this->path))

Ist hier die Prüfung wirklich notwendig? Kannst du nicht pauschal am `?` trennen. Ggf. ist $queryParams dann nicht gefüllt.

>  
-        $trailingSlash = self::shouldAppendTrailingSlash() ? "/" : "";
+        $trailingSlash = self::shouldAppendTrailingSlash() && !$this->hasTralingSlash($this->path) ? "/" : "";

Du solltest nach dem Splitten an `?` den Trailing Slash pauschal entfernen, falls vorhanden und ihn dann ggf. wieder hinzufügen. So fängst du auch den Fall, dass ein Slash da ist aber nicht da sein soll ab.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/657#pullrequestreview-311095842

Test.test.test

2020-05-13 16:13 UTC, maxhelligeplenty commented
Hallo  ,
felixdausch requested changes on this pull request.



>          }
         elseif(strlen($this->path) == 0)
         {
             return '/';
         }
 
-        return $this->path . $trailingSlash;
+        return $this->path . $trailingSlash . $queryParams;

```
list($path, $queryParams) = explode('?', $this->path);
if($path[strlen($path)-1] == '/')
{
    $path = substr($path, 0, -1);
}
$queryParams = strlen($queryParams) ? "?" . $queryParams : "";

$trailingSlash = self::shouldAppendTrailingSlash() ? "/" : "";

if ( $includeLanguage && strpos($path, '/'.$this->lang) !== 0)
{
    return '/' . $this->lang . $path . $trailingSlash . $queryParams;
}
elseif(strlen($path) == 0)
{
    return  "/";
}

return $path . $trailingSlash . $queryParams
```

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/657#pullrequestreview-311134699

Test.test.test

2020-05-13 16:17 UTC, maxhelligeplenty commented
Hallo  ,
felixdausch approved this pull request.





-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/plentymarkets/plugin-io/pull/657#pullrequestreview-311142945

Test.test.test