Feature/vdi/main
plentymarkets/plugin-io pull request #718
Opened 2020-01-14 13:49 UTC by stentrop

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2020-02-19 17:12 UTC, stentrop commented on src/Services/ItemSearch/Factories/VariationSearchResultFactory.php
> + */
@Dominik2809 

Ziehen wir  das auch noch um ?

2020-02-26 16:26 UTC, stentrop commented
Restart tests.

2020-02-27 10:03 UTC, Dominik2809 submitted a review, later dismissed

2020-02-27 10:05 UTC, felixdausch requested changes
Noch zu besprechen:
- [ ] Ist es sinnvoll, den SessionStorageService 1:1 in den Kern zu überführen? Aktuell werden kernseitig nur `CURRENCY`  und `SHIPPING_PRIVACY_HINT_ACCEPTED` verwendet. Viele der anderen Einträge landen jetzt im Kern, obwohl es nicht nötig ist und es vielleicht schönere Möglichkeiten gäbe, wenn es schon in den Kern überführt wird.

2020-02-27 10:05 UTC, felixdausch commented on config.json
> +                    "deprecated": true,
Wir haben den TemplateConfigService in IO doch nicht deprecated. Die Einstellung sollte demnach auch nicht deprecated werden.

2020-02-27 10:05 UTC, felixdausch commented on src/Controllers/ItemController.php
> +        if ($variationId > 0 && (int)$templateConfigService->getInteger('item.show_please_select') == 1) {
```suggestion
        if ($variationId > 0 && $templateConfigService->getInteger('item.show_please_select') == 1) {
```
->getInteger() sollte schon einen integer-Wert liefern.

2020-02-27 10:05 UTC, felixdausch commented on src/Controllers/ItemController.php
> +                    $itemResult['item']['documents'][0]['data']['currentData']['category']
Ist hier das komplette Category-Objekt enthalten oder nur die ID?

2020-02-27 10:08 UTC, stentrop commented on config.json
> +                    "deprecated": true,
Hier hatte David mal gesagt wir sollen es ausblenden, von daher haben wir es deprecated

2020-02-27 10:13 UTC, stentrop commented on src/Controllers/ItemController.php
> +                    $itemResult['item']['documents'][0]['data']['currentData']['category']
Hier ist das komplette Category Object drin

2020-02-27 10:22 UTC, felixdausch requested changes
- [ ] Ich persönlich finde es unschön, im TwigServiceContainer jetzt noch Repository-Getter einzuführen, um auf die neuen Klassen zu verweisen. Dadurch kommen Dopplungen zustande, die schwer nachvollziehbar sind, z.B. services.webstoreConfig.XYZ vs. services.webstoreConfigurationRepository.XYZ
- [ ] Die Klassen, die in den Kern überführt wurden, wurden korrekterweise deprecated. Gleichzeitig wurde aber in diesen Klassen die Verwendung alle veralteten Services auf neue Kern-Klassen angepasst. Dadurch mussten sehr viele Klassen & Methoden ins Interface aufgenommen werden. Ist das wirklich nötig?

2020-02-27 10:22 UTC, felixdausch commented on src/Helper/CurrencyConverter.php
> +        return $checkoutRepository->getCurrency();
Warum hier die Anpassung auf die neue Schnittstelle? Die ganze Klasse ist ja sowieso deprecated.

2020-02-27 10:22 UTC, felixdausch commented on src/Helper/StringUtils.php
> +        return \Plenty\Modules\Webshop\Helpers\StringUtils::string4URL($n);
Mapping auf Kern-Klasse nicht nötig? => Klasse muss ggf. nicht ins Interface

2020-02-27 10:22 UTC, felixdausch commented on src/Helper/VariationPriceList.php
>          $this->liveShoppingRepo     = $liveShoppingRepo;
Klasse deprecated => Ersetzung durch neue Klassen nicht nötig

2020-02-27 10:34 UTC, felixdausch requested changes

2020-02-27 10:34 UTC, felixdausch commented on src/Models/LocalizedOrder.php
> +        $orderVariations = $itemSearchService->getResults([
Warum der Umbau von `getResult()` auf `getResults()[0]`?

2020-02-27 10:59 UTC, stentrop commented
Restart tests.

2020-02-27 15:10 UTC, stentrop commented
Restart tests.

2020-02-27 15:17 UTC, stentrop commented
Restart tests.

2020-02-27 15:22 UTC, felixdausch approved these changes

2020-02-27 15:22 UTC, merged