UPDATE ignore recaptcha without constent
plentymarkets/plugin-io pull request #753
Opened 2020-02-24 13:50 UTC by lks-mtzn

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2020-02-24 14:54 UTC, felixdausch requested changes

2020-02-24 14:54 UTC, felixdausch commented on src/Helper/ReCaptcha.php
> +        $blockCookies = $templateConfigService->get('global.block_cookies');
```suggestion
        $blockCookies = $templateConfigService->getBoolean('global.block_cookies');
```

2020-02-24 14:54 UTC, felixdausch commented on src/Helper/ReCaptcha.php
> +        else if ($blockCookies == "true" && !$isConsented)
```suggestion
        else if ($blockCookies && !$isConsented)
```

2020-02-26 14:29 UTC, Dominik2809 commented
Nach dem Merge von VDI in Ceres und IO beta muss die Verwendung von TemplateConfigService auf TemplateConfigRepositoryContract aus dem Kern angepasst werden.

2020-02-26 15:22 UTC, felixdausch approved these changes

2020-02-27 10:52 UTC, merged