show shipping costs also when is completly paid with coupon
plentymarkets/plugin-io pull request #770
Opened 2020-03-20 10:37 UTC by stentrop

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2020-03-24 13:26 UTC, Dominik2809 commented on src/Services/BasketService.php
> +        $sessionStorageRepository = app(SessionStorageRepositoryContract::class);
```suggestion
        $sessionStorageRepository = pluginApp(SessionStorageRepositoryContract::class);
```

2020-04-14 06:22 UTC, stentrop commented
Vorher: ![Bildschirmfoto 2020-04-14 um 07 43 17](https://user-images.githubusercontent.com/13133283/79192502-22279600-7e29-11ea-8c2d-95105b1b0a69.png)

2020-04-14 06:23 UTC, stentrop commented
Nachher:
![Bildschirmfoto 2020-04-14 um 07 46 32](https://user-images.githubusercontent.com/13133283/79192530-2c499480-7e29-11ea-949e-5d35e35afd41.png)

2020-04-14 06:45 UTC, estafilarakis requested changes

2020-04-14 06:45 UTC, estafilarakis commented on src/Services/BasketService.php
> +            $couponService = new \Plenty\Modules\Order\Coupon\Services\CouponService();
Das finde ich etwas unschön.
Es gibt die Facade `CouponHelper`, welche diesen  Service benutzt.
Sonst würde ich eher sowas vorschlagen, wenn es im IO Plugin möglich ist:
```php
$couponService = pluginApp(CouponService::class);
```

2020-04-14 06:45 UTC, estafilarakis commented on src/Services/BasketService.php
> +            $isNet = $customer->showNetPrice;
Hier bin ich mir unsicher, ob es so korrekt ist!
Ob eine Rechnung brutto oder netto wird, kann man nicht am Kontakt ablesen. Was man am Kontakt bzw. seiner Kundenklasse ablesen kann ist, ob die Anzeige der Preise brutto oder netto ist!
Evtl. sollten wir hierüber nochmal kurz skypen.

2020-04-14 06:45 UTC, estafilarakis commented on src/Services/BasketService.php
> +        if (count($basket['totalVats']) <= 0 && $isNet) {
Siehe oben.

2020-04-14 07:26 UTC, estafilarakis approved these changes

2020-04-14 14:02 UTC, merged