Fix/step by step nav
plentymarkets/plugin-io pull request #887
Opened 2020-09-14 13:17 UTC by lks-mtzn

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2020-09-16 12:24 UTC, stentrop requested changes

2020-09-16 12:24 UTC, stentrop commented on src/Services/CategoryService.php
>              }
```suggestion
            if ($category['id'] !== $branch[$branchKey]) {
                continue;
            } elseif ($category['id'] == $categoryId) {
                $result = $category;
                break;
            } elseif (count($category['children'])) {
                $result = $this->findInCategoryTree($category['children'], $branch, $level + 1);
                break;
            }
```

2020-09-16 12:50 UTC, stentrop approved these changes

2020-09-18 08:18 UTC, lks-mtzn commented
.restart Tests

2020-09-18 15:26 UTC, lks-mtzn commented
Restart Tests.

2020-09-18 15:27 UTC, lks-mtzn commented
Restart tests.

2020-09-22 17:35 UTC, merged