Brexit: Added date param to methods
plentymarkets/plugin-io pull request #915
Opened 2020-11-04 15:49 UTC by ilyes-plenty

### All changes meet the following requirements
- [x] Changelog entry was added (Is created with the release of the feature)
- [x] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [x] Plugin can be built

@plentymarkets/ceres-io 
@plentymarkets/team-order-payment 

[Kanbanize](https://plentymarkets.kanbanize.com/ctrl_board/75/cards/137626/details/)
@plentymarkets/team-order-payment

Core-logic: https://github.com/plentymarkets/php-py/pull/13644
https://github.com/plentymarkets/module-order/pull/739
https://github.com/plentymarkets/php-py/pull/13653
https://github.com/plentymarkets/php-pl/pull/10473

2020-11-09 08:46 UTC, raphael-adam requested changes

2020-11-09 08:46 UTC, raphael-adam commented on src/Services/BasketService.php
> +            date("Y-m-d", $basket['createdAt'])
Hier macht es wie gesagt für mich keinen Sinn, das Erstellungsdatum des Warenkorbs zu nehmen. Ich denke die Stelle muss nicht angepasst werden.

2020-11-09 08:46 UTC, raphael-adam commented on src/Services/OrderTotalsService.php
> +                            $entryDate->date->toDateString()
`$entryDate` kann theoretisch auch `null` sein, da über `first()` geladen. Hier sollte noch eine Prüfung rein.

2020-11-09 09:26 UTC, raphael-adam approved these changes

2020-11-09 09:36 UTC, felixdausch approved these changes
**Bitte erst mergen, sobald die kernseitigen Anpassungen in stable7 angekommen sind!**

2020-11-10 07:45 UTC, estafilarakis approved these changes

2020-11-27 12:16 UTC, merged