Add: Method to filter item variations by id
plentymarkets/plugin-io pull request #998
Opened 2021-05-21 15:03 UTC by maxiroellplenty

require -> https://github.com/plentymarkets/plugin-ceres/pull/2875

### All changes meet the following requirements
- [ ] Changelog entry was added
- [ ] Changes have been documented
- [ ] Changes have been tested by the author
- [ ] Changes have been tested by the reviewer
- [ ] Plugin can be built

@plentymarkets/ceres-io

2021-05-27 07:33 UTC, stentrop requested changes

2021-05-27 07:33 UTC, stentrop commented on src/Extensions/Functions/FindItemVariation.php
> +        return array_shift(array_filter($variations, function ($variation) use ($variationId) {
Theoretisch könnte er in variations auch 2x die gleiche Variante haben was zu einem Fehler führen sollte

2021-05-27 07:33 UTC, stentrop commented on src/Extensions/Functions/FindItemVariation.php
> +    public function findItemVariationById( $variationId, $variations )
Bessere Dokumentation, was genau wird reingegeben (welche struktur) und was wird zurückgegeben.

2021-06-01 07:08 UTC, Dominik2809 approved these changes

2021-06-01 07:15 UTC, stentrop approved these changes

2021-06-01 07:15 UTC, merged